import SwiftUI

/**
 This code was fully generated by Claude. 
 */
struct ConfettiView: View {
    @State private var particles: [ConfettiParticle] = []
    @State private var startTime = Date.now

    private let colors: [Color] = [
        Color(.purple, 500), Color(.purple, 300),
        Color(.yellow, 400), Color(.yellow, 300),
        .green, .pink, .orange, .mint
    ]

    var body: some View {
        TimelineView(.animation) { timeline in
            let elapsed = timeline.date.timeIntervalSince(startTime)
            Canvas { context, size in
                for particle in particles {
                    let age = elapsed - particle.delay
                    guard age > 0 else { continue }

                    let progress = age / particle.duration
                    guard progress < 1 else { continue }

                    let x = particle.startX * size.width + sin(age * particle.wobbleSpeed) * particle.wobbleAmount
                    let y = particle.startY + age * particle.fallSpeed
                    let rotation = Angle.degrees(age * particle.rotationSpeed)
                    let opacity = progress < 0.8 ? 1.0 : 1.0 - (progress - 0.8) / 0.2

                    context.opacity = opacity
                    context.translateBy(x: x, y: y)
                    context.rotate(by: rotation)

                    let rect = CGRect(
                        x: -particle.width / 2,
                        y: -particle.height / 2,
                        width: particle.width,
                        height: particle.height
                    )

                    if particle.isCircle {
                        context.fill(
                            Path(ellipseIn: rect),
                            with: .color(particle.color)
                        )
                    } else {
                        context.fill(
                            Path(roundedRect: rect, cornerRadius: 1),
                            with: .color(particle.color)
                        )
                    }

                    context.rotate(by: -rotation)
                    context.translateBy(x: -x, y: -y)
                }
            }
        }
        .allowsHitTesting(false)
        .onAppear {
            particles = (0..<80).map { _ in
                ConfettiParticle(
                    startX: CGFloat.random(in: 0...1),
                    startY: CGFloat.random(in: -100 ... -20),
                    width: CGFloat.random(in: 4...10),
                    height: CGFloat.random(in: 6...14),
                    isCircle: Bool.random(),
                    color: colors.randomElement()!,
                    fallSpeed: CGFloat.random(in: 80...200),
                    wobbleSpeed: Double.random(in: 2...6),
                    wobbleAmount: CGFloat.random(in: 20...60),
                    rotationSpeed: Double.random(in: 60...360),
                    delay: Double.random(in: 0...1.0),
                    duration: Double.random(in: 3...5)
                )
            }
        }
    }
}

private struct ConfettiParticle {
    let startX: CGFloat
    let startY: CGFloat
    let width: CGFloat
    let height: CGFloat
    let isCircle: Bool
    let color: Color
    let fallSpeed: CGFloat
    let wobbleSpeed: Double
    let wobbleAmount: CGFloat
    let rotationSpeed: Double
    let delay: Double
    let duration: Double
}
